FROM openjdk:8-jdk

COPY ./httpclients-withpooling/build/libs/withpoolingservice-0.1.0.jar /data/poolingexplorations/withpoolingservice-0.1.0.jar

WORKDIR /data/poolingexplorations

CMD ["java","-jar","withpoolingservice-0.1.0.jar"]

EXPOSE 8082
